site_name: Guides
# site_url: https://example.com/
# nav:
#     - Getting Started: index.md
#     - About: about.md
#     - Contact: contact.md
# theme: readthedocs
plugins:
  - search
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: false
      nav_repos:
        - name: backstage
          import_url: https://github.com/backstage/backstage
          # forward slash is needed in '/README.md' so that only the README.md in the root
          # directory is imported and not all README.md files.
          imports: [
            docs/publishing.md, docs/integrations/index.md, /README.md,
            # asset files needed
            docs/assets/*
            ]
        - name: fast-api
          import_url: https://github.com/tiangolo/fastapi
          imports: [docs/en/docs/index.md]
        - name: mono-repo
          import_url: https://github.com/backstage/mkdocs-monorepo-plugin
          imports: [docs/en/docs/index.md,docs/CODE-OF-CONDUCT.md]

nav:
  - Introduction:
        - Backstage: backstage/docs/publishing.md
        - Monorepo: mono-repo/docs/CODE-OF-CONDUCT.md
      # - Integration: backstage/docs/integrations/index.md
  - Publishing-Api: fast-api/docs/en/docs/index.md


  
  # - FastAPiHome: fast-api/docs/en/docs/index.md
  # - FastAPI: fast-api/docs/en/docs/index.md
  # you can still use the !import statement
  # - MkdocStrings: '!import https://github.com/mkdocstrings/mkdocstrings'
  # nav:

  # - Introduction:

  #     - backstageIntroduciton: backstage/README.md

  #     - fast-apiIntroduciton: ast-api/docs/en/docs/index.md

  # - Publishing: backstage/docs/publishing.md

  # - FastAPiHome: fast-api/docs/en/docs/index.md